#!/bin/bash

cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution
tmpDir=$(mkdir -p "/cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/tmp.a5fb6f61" && echo "/cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/tmp.a5fb6f61")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution

)
outeec2cb57="${tmpDir}/out.$$" erreec2cb57="${tmpDir}/err.$$"
mkfifo "$outeec2cb57" "$erreec2cb57"
trap 'rm "$outeec2cb57" "$erreec2cb57"' EXIT
tee '/cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution/stdout' < "$outeec2cb57" &
tee '/cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution/stderr' < "$erreec2cb57" >&2 &
(
cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution


set -e
mkdir -p "$(dirname ./samples//female.g.vcf.gz)"
gatk --java-options -Xmx4G \
HaplotypeCaller \
-R /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/inputs/1489649706/reference.fasta \
-O ./samples//female.g.vcf.gz \
-I /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/inputs/1489649706/female.bam \
 \
-L /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/inputs/181539600/scatter-0.bed \
  \
-D /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/inputs/1489649706/expected.vcf.gz \
 \
 \
 \
--emit-ref-confidence GVCF \
 \
)  > "$outeec2cb57" 2> "$erreec2cb57"
echo $? > /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution
sync


)
mv /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution/rc.tmp /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-singleSampleCalling/shard-1/SingleSampleCalling/eec2cb57-9994-4799-929c-fdd9e308526c/call-callAutosomal/shard-0/execution/rc
