#!/bin/bash

cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution
tmpDir=$(mkdir -p "/cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/tmp.c181f45d" && echo "/cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/tmp.c181f45d")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution

)
out8b79bccf="${tmpDir}/out.$$" err8b79bccf="${tmpDir}/err.$$"
mkfifo "$out8b79bccf" "$err8b79bccf"
trap 'rm "$out8b79bccf" "$err8b79bccf"' EXIT
tee '/cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution/stdout' < "$out8b79bccf" &
tee '/cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution/stderr' < "$err8b79bccf" >&2 &
(
cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution


set -e
cut -f1,2 /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/inputs/1489649706/reference.fasta.fai > sizes.genome
bedtools complement \
-g sizes.genome \
-i /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/inputs/1203273806/merged.bed \
> autosomal_regions.bed
)  > "$out8b79bccf" 2> "$err8b79bccf"
echo $? > /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution
sync


)
mv /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution/rc.tmp /cromwell-executions/MultisampleCalling/49fed616-9748-4aca-bd2e-90c0ccb43116/call-calculateRegions/CalculateRegions/8b79bccf-6989-4068-8cb5-a811f0aff13f/call-inverseBed/execution/rc
